version: '2'

services:
  api:
    container_name: lex_dop_api_graphql
    build: ./api
    ports:
      - '80:8080'
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
    volumes:
      - ./api/src:/app/api
  db:
    container_name: lex_dop_api_mysql
    ports:
      - '3306:3306'
    build: ./database
